gui:
  commandLogSize: 20
  border: "rounded"
  theme:
    inactiveBorderColor:
      - "#9b9ea4"
confirmOnQuit: false
promptToReturnFromSubprocess: false
os:
  edit: "nvim -u ~/.config/nvim/init.lua -c 'DiffviewOpen' {{filename}}"
  editAtLine: "nvim -u ~/.config/nvim/init.lua -c 'DiffviewOpen' {{filename}}"
  openLink: "brave {{link}}"

customCommands:
  - key: 'R'
    context: 'submodules' 
    command: 'git submodule update --init --recursive --force'
    output: popup
    description: "Force bulk init and update submodules recursively"
    prompts:
      - type: 'confirm'
        title: 'Are you sure?'
        body: 'This will force update all submodules recursively.'
